### ISSUE TITLE
IPsec Requirement wants an Extra EA

### ISSUE THREAD

**Issue by robertmclemons** [commoncriteria/vpnclient#1]
The IPSec requirement wants an EA for the component as well as for each element. I don't think we support this now, but maybe we should. Or we'll have to kludge this up for the EAs to output properly.

**Comment by jmcdaniels** [comment]
It seems to build fine now at least.

**Comment by robertmclemons** [comment]
This is supported now by the level="component" and level="element" attributes on the aactivity element..
