### ISSUE TITLE
Auditable Events for Mandatory SFRs

### ISSUE THREAD

**Issue by plughy2** [commoncriteria/vpnclient#14]
Should section 5.5.1 - Auditable Events for Mandatory SFRs be included?  Auditable Events for Mandatory SFRs and Table 2 is inconsistent with FAU_GEN.1/VPN as that SFR is not a mandatory requirement.  It has always been optional.

**Comment by jmcdaniels** [comment]
FAU_GEN.1/VPN no longer listed in table.
