### ISSUE TITLE
FCS_IPSEC_EXT.1.8

### ISSUE THREAD

**Issue by plughy2** [commoncriteria/vpnclient#15]
Suggest making the **optional** DH Groups consistent with what is defined in FCS_IPSEC_EXT.1.11 of the VPN GW Module. FCS_IPSEC_EXT.1.1 in VPNGW permits the following optional DH Groups:  14, 15, 16, 17, 18, 21, 24.  FCS_IPSEC_EXT.1.8 in the VPN Client permits the following optional DH Groups:  14, 15, 24

**Comment by jmcdaniels** [comment]
Aligning groups with VPNGW.
