### ISSUE TITLE
Client credentials

### ISSUE THREAD

**Issue by plughy2** [commoncriteria/vpnclient#17]
https://github.com/commoncriteria/vpnclient/blob/c6e2e0727c7a24ed2793a437b34d8a401fa4d855/input/vpnclient.xml#L4093

The phrase in the Application Note for FMT_SMF.1/VPN:  "Client credentials ... may also include a username/password" is now outdated.  Perhaps that could be changed to ...may also include selected PSK factors listed in FIA_PSK_EXT.1.2

**Comment by jmcdaniels** [comment]
Changed reference to PSK.
