### ISSUE TITLE
Verify HOTP/TOTP

### ISSUE THREAD

**Issue by plughy2** [commoncriteria/vpnclient#18]
https://github.com/commoncriteria/vpnclient/blob/c6e2e0727c7a24ed2793a437b34d8a401fa4d855/input/vpnclient.xml#L4890

FIA_PSK_EXT.4.2 says HOTP is verified "before establishing an incoming connection."  Why incoming when its the client?  It seems this should read "before establishing a VPN connection"

Same question for FIA_PSK_EXT.5.2 and TOTP on line 4941

**Comment by jmcdaniels** [comment]
Added app note to clarify selection.
