### ISSUE TITLE
FCS_EAP_EXT.1.4 applies to server

### ISSUE THREAD

**Issue by plughy2** [commoncriteria/vpnclient#19]
https://github.com/commoncriteria/vpnclient/blob/c6e2e0727c7a24ed2793a437b34d8a401fa4d855/input/vpnclient.xml#L4420

FCS_EAP_EXT.1.4 says "The TSF shall not forward a EAP-success response if the client certificate is not valid according to FIA_X509_EXT.1."

This SFR is the same as in the gateway module.  As such, it does not apply to the client as it currently written.   EAP-success response comes from the server and wouldn't be forwarded by the client. The validity of the client's certificate also doesn't apply.  For these reasons, FCS_EAP_EXT.1.4 could be removed from the VPN Client module.

**Comment by jmcdaniels** [comment]
Concur, 1.4 will be removed from client module.
