### ISSUE TITLE
The Table 5: GPOS PP Security Problem Definition Consistency Rationale is empty in https://commoncriteria.github.io/pp/vpnclient/vpnclient.html#consecprob-OS

### ISSUE THREAD

**Issue by adelton** [commoncriteria/vpnclient#2]
The 6.1.2 section at https://commoncriteria.github.io/pp/vpnclient/vpnclient.html#consecprob-OS contains 7-line table which is empty. In https://www.niap-ccevs.org/MMO/PP/mod_vpnc_v2.2.pdf there's Table 5: GPOSPPSecurity Problem Definition Consistency Rationale there.

Looking at https://github.com/commoncriteria/vpnclient/blob/master/input/vpnclient.xml the `<con-mod/>` elements are in the input, however they don't get formatted in the HTML output.

**Comment by adelton** [comment]
The same issue is at https://commoncriteria.github.io/pp/vpnclient/vpnclient-release.html#consecprob-OS.

**Comment by jmcdaniels** [comment]
Updated tables populate properly.
