### ISSUE TITLE
FCS_EAP_EXT.1.1 and RFC of EAP-TTLS

### ISSUE THREAD

**Issue by Sinkmanu** [commoncriteria/vpnclient#20]
There is a typo in FCS_EAP_EXT.1.1, the RFC of EAP-TTLS is not correct. It does reference to RFC 5881 which is the RFC of "Bidirectional Forwarding Detection (BFD) for IPv4 and IPv6 (Single Hop)", EAP-TTLS is RFC 5281.

```
              <selectables>
                <selectable>EAP-TLS protocol as specified in RFC 5216</selectable>
                <selectable>EAP-TTLS as specified in RFC 5881</selectable>
              </selectables>
```

**Comment by jmcdaniels** [comment]
Fixed.
