### ISSUE TITLE
The Essential Security Requirements (ESR) link is broken

### ISSUE THREAD

**Issue by adelton** [commoncriteria/vpnclient#3]
The README.md document has a link
```
[Essential Security Requirements (ESR)](https://commoncriteria.github.io/pp/vpnclient/vpnclient-esr.html)
```
but accessing https://commoncriteria.github.io/pp/vpnclient/vpnclient-esr.html results in 404 File not found.

**Comment by jmcdaniels** [comment]
ESR now working properly.
